---
- name: Playbook para hacer el deploy de la aplicación web Wordpress
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: decargar wp-cli, moverlo a bin y darle permisos
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: a+x

    - name: borrar 
      shell: /bin/rm -rf /var/www/html*

    - name: descargar el codigo de wordpress
      command:
        wp core download \
        --locale=es_ES \
        --path=/var/www/html \
        --allow-root
        
    - name: Set up wp-config
      command:        
        wp config create \
        --dbname={{ db.name }} \
        --dbuser={{ db.user }} \
        --dbpass={{ db.password }} \
        --dbhost={{ ip.backend }} \
        --path=/var/www/html \
        --allow-root

    - name: install wp
      command:
        wp core install \
        --url={{ certbot.domain }} \
        --title="{{ wordpress.title }}" \
        --admin_user={{ wordpress.admin }} \
        --admin_password={{ wordpress.password }} \
        --admin_email={{ wordpress.email }} \
        --path=/var/www/html \
        --allow-root  

    - name: install plugin
      command:
        wp plugin install wps-hide-login --path=/var/www/html --allow-root

    - name: PermaLinks
      command: wp --path=/var/www/html plugin install permalink-manager --activate --allow-root

    - name: PermaLinks config
      command: wp --path=/var/www/html option update permalink_structure '/%postname%/' --allow-root
